# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: postgresql
  database: dbname
  username: dbuser
  password: dbpass


production:
  adapter: postgresql
  database: dbname
  username: dbuser
  password: dbpass
