# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: postgresql
  database: siena2
  username: siena	
  password: eBHHH3DrHR


production:
  adapter: postgresql
  database: siena2
  username: siena
  password: eBHHH3DrHR
